### PR TITLE
Feature/keyword extractor 

### LINKED ISSUE #4: Keyword extractor
Send the horoscope data—esp. the horoscope's "description"—to the keyword extractor, and extract relevant words

### PR DESCRIPTION
**Pull request by mnwana**
Add keyword extractor using  https://rapidapi.com/textprobe/api/textprobe/

Takes input of either feelings or topics and returns a value from the call.

### CODE REVIEW

**Comment by mnwana** [comment]
vs code reformatted automatically so it looks like there are more changes than there are

**Comment by noah35becker** [comment]
This looks great!

I see that you're only passing the horoscope's description to the keyword extractor, which makes sense. I just wanna make sure that color, lucky number, and mood stay in the mix somehow—could we push all three of them on to the end of the 'topics' output array (without actually passing them to the keyword extractor)? Or, maybe push the color + lucky number onto the end of the 'topics' array, and push the mood onto the end of the 'feelings' array (I know 'feelings' is just a string as of now, but we could make it an array)?

I'm also wondering about is the practical purpose of separating out topics vs feelings. It's great that the keyword extractor offers both features—what about just throwing all the topics + feelings terms together in one array, and letting Spotify have at it from there? Unless there's a reason to keep them separate?

Even if we were to keep topics vs feelings separated, currently this code is running two separate textprobe API calls, which I think will slow down the program unnecessarily. What about removing the `extractType` parameter from the `extractFromText` function, and returning a single object that contains topics and feelings both (unless we decide to combine topics and feelings, in which case this idea is moot)? Something like:
```
{
	topics: [topic1, topic2, topic3…, color, luckyNum],
	feelings: [feeling, mood]
}
```

One final thought, on the horoscope object's color specifically—sometimes it's two words, e.g. 'rose pink' or 'sky blue'. What about automatically splitting it into individual words, so that Spotify might only receive 'rose', or only 'pink'? It could make the final result cooler, more abstract. I mean, we could even have 'rose', 'pink', and 'rose pink' all three in the pot, why not?

**Comment by mnwana** [comment]
topics and feelings are separated as they have to be two api calls. i created an extractType input to the function to avoid duplicating code since they only have 2 lines that are different. i updated the return statements to include those values for now (i'm assuming we'll want to just call the next function for spotify). if we're worried about speed we'd likely not calling feelings. it's a little duplicative but i included the option in case we wanted it

**Review by noah35becker — APPROVED** [review]
Ah, I totally missed that `extractType` is a part of the fetch URL itself, gotchu! Cool, this looks good to me

**Review by claudiayile — APPROVED** [review]

**Pull request merged**
